### ISSUE TITLE
Make it possible to add custom HTTP headers

### ISSUE THREAD

**Issue by FrankW76** [jiakuan/gwt-uploader#1]
Using XHR2 it is possible to inject custom HTTP headers, and upload a file at the same time. This is not  possible using the classic way.

Since this library is using XHR2 it would be a good addition if adding HTTP headers would also be possible in this library.

**Comment by jiakuan** [comment]
Will have a look when I have a chance.
Any pull requests are welcome.

**Comment by FrankW76** [comment]
See my pull request

#2 

Tested in my own project and working

**Comment by jiakuan** [comment]
Great.
Have created a new release 1.2.1, which will reach Maven central perhaps in a few hours.
